### ISSUE TITLE
Notice during opcache restart

### ISSUE THREAD

**Issue by pako-pl** [rlerdorf/opcache-status#25]
The following function in the `opcache.php` script generates a PHP notice during an OpCache restart:

public function getScriptStatusCount() {
    return count($this->_status["scripts"]);
  }

The 'scripts' key is not set when an opcache restart is pending after calling opcache_reset().

**Comment by cfoellmann** [comment]
can you open an issue/PR here https://github.com/wp-cloud/opcache-status/issues ?

**Comment by pako-pl** [comment]
I was not able to reproduce the issue testing on PHP 7.0.11 with the latest version of opcache-status script from this repository. So I'm closing the issue for now.
