### ISSUE TITLE
PHP-parsed .html files are not listed, are they cached?

### ISSUE THREAD

**Issue by teamits** [rlerdorf/opcache-status#37]
Most files on our site are named as .html files but are actually PHP code and parsed as such.  The web server is correctly running them through PHP, however, the OpCache status page lists only .php files on its Scripts tab.  Is OpCache only listing .php files? Or are .html files not being cached, and if so why not if they are being run through PHP?  It's been a long time since I looked but I don't recall APC excluding those on our old server...

**Comment by rlerdorf** [comment]
I can't reproduce that here. My php-parsed .html files are listed just fine and there is nothing in neither opcache nor in the opcache-status script that cares about file extensions.

**Comment by teamits** [comment]
Hi Rasmus, thank you for double checking this.  It turns out I managed to set .html files to use the PHP handler which ran as CGI, while .php files were using the mod_fcgid handler which is the only stats that OpCache can see, of course, since the CGI terminates.  It didn't occur to me it was possible to do both on one site, but it turns out computers follow directions they're given.  :)
